---
# IPv4 Kernel Settings tasks file for ansible-role-kernel-settings/

- name: "Disable accepting of all IPv4 ICMP redirects"
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: '0'
    state: present

- name: "Disable default accepting of all IPv4 ICMP redirects"
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: '0'
    state: present

- name: "Disable default sending of all IPv4 ICMP redirects"
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: '0'
    state: present

- name: "Disable sending of all ICMP redirects"
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: '0'
    state: present

- name: "Disable sending of all secure ICMP redirects"
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.secure_redirects
    value: '0'
    state: present

- name: "Disable default sending of all secure ICMP redirects"
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.secure_redirects
    value: '0'
    state: present

- name: "Disable all source routed packets are not accepted"
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: '0'
    state: present

- name: "Disable default source routed packets are not accepted"
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: '0'
    state: present

- name: "Enable all Reverse Path Filtering"
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: '1'
    state: present

- name: "Enable default Reverse Path Filtering"
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: '1'
    state: present

- name: "Enable all TCP SYN Cookies"
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: '1'
    state: present

- name: "Log all suspicious packets"
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.log_martians
    value: '1'
    state: present

- name: "Default Log all suspicious packets"
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.log_martians
    value: '1'
    state: present

- name: "Disable TCP Timestamps"
  ansible.posix.sysctl:
    name: net.ipv4.tcp_timestamps
    value: '0'
    state: present

- name: "Disable IP Forwarding"
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '0'
    state: present

- name: "Disable broadcast ICMP requests"
  ansible.posix.sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: '1'
    state: present

- name: "Disable bogus ICMP responses"
  ansible.posix.sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: '1'
    state: present

- name: "Flush IPv4 Routes"
  ansible.posix.sysctl:
    name: net.ipv4.route.flush
    value: '1'
    state: present

- name: "Turn off tcp_sack for IPv4"
  ansible.posix.sysctl:
    name: net.ipv4.tcp_sack
    value: '0'
    state: present
    reload: yes
