---
# IPv6 Kernel Settings tasks file for ansible-role-kernel-settings/

- name: "Disable IPv6 for all interfaces"
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    state: present

- name: "Disable default IPv6 for all interfaces"
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    state: present

- name: "Disable IPv6 forwarding for all interfaces"
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '0'
    state: present

- name: "Disable accepting of all IPv6 ICMP redirects"
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_redirects
    value: '0'
    state: present

- name: "Disable default accepting of all IPv6 ICMP redirects"
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.accept_redirects
    value: '0'
    state: present
    reload: yes
