---
# tasks file for ansible-role-kernel-settings/

- name: "Include tasks from IPv6 playbook"
  ansible.builtin.include_tasks: ipv6.yaml

- name: "Include tasks from IPv4 playbook"
  ansible.builtin.include_tasks: ipv4.yaml

- name: "Include tasks from Kernel Messaging Settings playbook"
  ansible.builtin.include_tasks: kernel_message.yaml

- name: "Include tasks from Virtual Address Space Settings playbook"
  ansible.builtin.include_tasks: virt_addr.yaml

- name: "Include tasks from Yama Kernel Settings playbook"
  ansible.builtin.include_tasks: yama.yaml
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_major_version'] >= '7'
