---
# Virtual Address Space Settings tasks file for ansible-role-kernel-settings/

- name: "Enable/Enforce Randomized Layout of Virtual Address Space"
  ansible.posix.sysctl:
    name: kernel.randomize_va_space
    value: '2'
    state: present
